//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JZWineNB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int CommentID { get; set; }
        public Nullable<decimal> Rate { get; set; }

        [DataType(DataType.Date)] 
        [DisplayFormat(DataFormatString = "{0:dd MM yy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Date { get; set; }

        [Display(Name ="Comment")]
        public string Comment1 { get; set; }
        public int DrinkerID { get; set; }
        public int WineID { get; set; }
    
        public virtual Drinker Drinker { get; set; }
        public virtual Wine Wine { get; set; }
    }
}
